### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by Theitfixer85** [evoactivity/PlutoIPTV#21]
So for a few hours it worked perfectly but now I am getting the following error across all device I try to run it on with no change from when it was working
Note I have **** out my pc username

```
TypeError: Cannot read property 'path' of undefined
    at C:\Users\****\AppData\Roaming\npm-cache\_npx\11920\node_modules\pluto-iptv\index.js:215:56
    at Array.forEach (<anonymous>)
    at C:\Users\****\AppData\Roaming\npm-cache\_npx\11920\node_modules\pluto-iptv\index.js:153:27
    at Array.forEach (<anonymous>)
    at C:\Users\****\AppData\Roaming\npm-cache\_npx\11920\node_modules\pluto-iptv\index.js:136:12
    at Request._callback (C:\Users\****\AppData\Roaming\npm-cache\_npx\11920\node_modules\pluto-iptv\index.js:52:7)
    at Request.self.callback (C:\Users\****\AppData\Roaming\npm-cache\_npx\11920\node_modules\pluto-iptv\node_modules\request\request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (C:\Users\****\AppData\Roaming\npm-cache\_npx\11920\node_modules\pluto-iptv\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:314:20)
```

**Comment by Theitfixer85** [comment]
Seems to be working again - so I presume it was an issue with the last 12 hour grab

**Comment by evoactivity** [comment]
Ok, I'll keep this open as I can make it so it doesn't error out if it can't find the data it is requesting.

**Comment by Theitfixer85** [comment]
I'm still getting this error a lot so a fix would be good
