### ISSUE TITLE
Another problem with todays run do your magic :)

### ISSUE THREAD

**Issue by yarafie** [evoactivity/PlutoIPTV#23]
.Another problem with todays run do your magic :)

last part of the run below.
.
.
[INFO] Adding instance of Sunshine Superman to channel Pluto TV Documentaries.
[INFO] Adding instance of Shaolin One to channel Pluto TV Documentaries.
/storage/emulated/0/IPTV/PlutoIPTV/index.js:218
                attrs: { src: programme.episode.poster.path},
                                                       ^

TypeError: Cannot read properties of undefined (reading 'path')
    at /storage/emulated/0/IPTV/PlutoIPTV/index.js:218:56
    at Array.forEach (<anonymous>)
    at /storage/emulated/0/IPTV/PlutoIPTV/index.js:156:27
    at Array.forEach (<anonymous>)
    at /storage/emulated/0/IPTV/PlutoIPTV/index.js:139:12
    at Request._callback (/storage/emulated/0/IPTV/PlutoIPTV/index.js:55:7)
    at Request.self.callback (/storage/emulated/0/IPTV/PlutoIPTV/node_modules/request/request.js:185:22)
    at Request.emit (node:events:390:28)
    at Request.<anonymous> (/storage/emulated/0/IPTV/PlutoIPTV/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:390:28)

**Comment by yarafie** [comment]
Started working again. So closing the issue
